package br.com.project.modelo;

public enum EnumTipoLogradouro {

	A("Área", true),
	AC("Acesso", false),
	ACA("Acampamento", false),
	ACL("Acesso Local", false),
	AD("Adro", false),
	AE("Área Especial", false),
	AER("Aeroporto", true),
	AL("Alameda", true),
	AMD("Avenida Marginal Direita", false),
	AME("Avenida Marginal Esquerda", false),
	AN("Anel Viário", false),
	ANT("Antiga Estrada", false),
	ART("Artéria", false),
	AT("Alto", false),
	ATL("Atalho", false),
	A_V("Área Verde", false),
	AV("Avenida",true),
	AVC("Avenida Contorno", false),
	AVM("Avenida Marginal", false),
	AVV("Avenida Velha", false),
	BAL("Balneário", false),
	BC("Beco", false),
	BCO("Buraco", false),
	BEL("Belvedere", false),
	BL("Bloco", false),
	BLO("Bal�o", false),
	BLS("Blocos", false),
	BLV("Bulevar", false),
	BSQ("Bosque", false),
	BVD("Boulevard", false),
	BX("Baixa", false),
	C("Cais", false),
	CAL("Calçaada", false),
	CAM("Caminho", false),
	CAN("Canal", false),
	CH("Chácara", false),
	CHA("Chapadão", false),
	CIC("Ciclovia", false),
	CIR("Circular", false),
	CJ("Conjunto", false),
	CJM("Conjunto Mutirão", false),
	CMP("Complexo Viário", false),
	COL("Colônia", false),
	COM("Comunidade", false),
	CON("Condomônio", false),
	COR("Corredor", false),
	CPO("Campo", true),
	CRG("Córrego", false),
	CTN("Contorno", false),
	DSC("Descida", false),
	DSV("Desvio", false),
	DT("Distrito", true),
	EB("Entre Bloco", false),
	EIM("Estrada Intermunicipal", false),
	ENS("Enseada", false),
	ENT("Entrada Particular", false),
	EQ("Entre Quadra", false),
	ESC("Escada", false),
	ESD("Escadaria", false),
	ESE("Estrada Estadual", false),
	ESI("Estrada Vicinal", false),
	ESL("Estrada de Ligação", false),
	ESM("Estrada Municipal", false),
	ESP("Esplanada", true),
	ESS("Estrada de Servidão", false),
	EST("Estrada", true),
	ESV("Estrada Velha", false),
	ETA("Estrada Antiga", false),
	ETC("Estação", true),
	ETD("Estádio", false),
	ETN("Estância", false),
	ETP("Estrada Particular", false),
	ETT("Estacionamento", false),
	EVA("Evangélica", false),
	EVD("Elevada", false),
	EX("Eixo Industrial", false),
	FAV("Favela", true),
	FAZ("Fazenda", true),
	FER("Ferrovia", false),
	FNT("Fonte", false),
	FRA("Feira", true),
	FTE("Forte", false),
	GAL("Galeria", false),
	GJA("Granja", false),
	HAB("Núcleo Habitacional", false),
	IA("Ilha", false),
	IND("Indeterminado", false),
	IOA("Ilhota", false),
	JD("Jardim", true),
	JDE("Jardinete", false),
	LD("Ladeira", true),
	LGA("Lagoa", true),
	LGO("Lago", true),
	LOT("Loteamento", true),
	LRG("Largo", true),
	LT("Lote", false),
	MER("Mercado", false),
	MNA("Marina", false),
	MOD("Modulo", false),
	MRG("Projeção", false),
	MRO("Morro", true),
	MTE("Monte", false),
	NUC("Núcleo", true),
	NUR("Núcleo Rural", false),
	OUT("Outeiro", false),
	PAR("Paralela", false),
	PAS("Passeio", false),
	PAT("Pátio", true),
	PC("Praça", true),
	PCE("Praça de Esportes", false),
	PDA("Parada", false),
	PDO("Paradouro", false),
	PNT("Ponta", false),
	PR("Praia", false),
	PRL("Prolongamento", false),
	PRM("Parque Municipal", false),
	PRQ("Parque", true),
	PRR("Parque Residencial", false),
	PSA("Passarela", true),
	PSG("Passagem", false),
	PSP("Passagem de Pedestre", false),
	PSS("Passagem Subterr�nea", false),
	PTE("Ponte", false),
	PTO("Porto", false),
	Q("Quadra", true),
	QTA("Quinta", false),
	QTS("Quintas", false),
	R("Rua", true),
	R_I("Rua Integração", false),
	R_L("Rua de Ligação", false),
	R_P("Rua Particular", false),
	R_V("Rua Velha", false),
	RAM("Ramal", false),
	RCR("Recreio", false),
	REC("Recanto", true),
	RER("Retiro", false),
	RES("Residencial", true),
	RET("Reta", false),
	RLA("Ruela", false),
	RMP("Rampa", false),
	ROA("Rodo Anel", false),
	ROD("Rodovia", true),
	ROT("Rotula", false),
	RPE("Rua de Pedestre", false),
	RPR("Margem", false),
	RTN("Retorno", false),
	RTT("Rotatória", false),
	SEG("Segunda Avenida", false),
	SIT("Sitio", true),
	SRV("Servidão", false),
	ST("Setor", true),
	SUB("Subida", false),
	TCH("Trincheira", false),
	TER("Terminal", false),
	TR("Trecho", true),
	TRV("Trevo", true),
	TUN("Túnel", false),
	TV("Travessa", true),
	TVP("Travessa Particular", false),
	TVV("Travessa Velha", false),
	UNI("Unidade", false),
	V("Via", true),
	V_C("Via Coletora", false),
	V_L("Via Local", false),
	VAC("Via de Acesso", false),
	VAL("Vala", false),
	VCO("Via Costeira", false),
	VD("Viaduto", true),
	V_E("Via Expressa", false),
	VER("Vereda", true),
	VEV("Via Elevado", false),
	VL("Vila", true),
	VLA("Viela", true),
	VLE("Vale", true),
	VLT("Via Litor�nea", false),
	VPE("Via de Pedestre", false),
	VRT("Variante", false),
	ZIG("Zigue-Zague", false);

	private String label;
	private Boolean ativo;

	private EnumTipoLogradouro(String label, Boolean ativo) {
		this.label = label;
		this.ativo = ativo;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}
	
	public Boolean getAtivo() {
		return ativo;
	}
	
	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}
}
